### ISSUE TITLE
Build error dll could not be found 

### ISSUE THREAD

**Issue by owlstack** [IEvangelist/Mirror#1]
Hello, 

I'm trying to run this project and I'm getting: 

 'C:\Users~\Mirror-master\Mirror.Speech\bin\x64\Debug\Mirror.Speech.dll' could not be found    

'C:\Users~\Mirror-master\Mirror.Extensions\bin\x64\Debug\Mirror.Extensions.dll' could not be found

And the same for Mirror.Core.dll. 

Do I just need to delete the objs/bin and try again?

**Comment by IEvangelist** [comment]
Wow, I'm surprised anyone is even active on this. How did you find this repo?

Yes, those folders should not even be in source control.  😄

**Comment by IEvangelist** [comment]
I actually just ran into this very issue locally. I did not check in the `obj` or `bin` directories, so I am assuming that this is some issue with **Visual Studio 2015** and the **UWP** platform for now. I was able to resolve this issue by deleting these directories, closing and reopening VS and then performing a _Rebuild All_
