### ISSUE TITLE
Requesting weather takes too long on slow connection

### ISSUE THREAD

**Issue by owlstack** [IEvangelist/Mirror#2]
I'm running the application on mobile emulator and locally on my device and it seems like it gets stuck on Requesting weather for quick some time on slow connection.

**Comment by IEvangelist** [comment]
Did you sign up for and use your openweather API key?

**Comment by owlstack** [comment]
No, thanks for the tip! What does the speech component do?

**Comment by IEvangelist** [comment]
Once the app loads, in the lower right hand corner there is a message that will read "I'm listening" ask it "what can I say" or "help". It will guide you!

**Comment by IEvangelist** [comment]
See the [`Configuration`](https://github.com/IEvangelist/Mirror#configuration) section, detailed in the `READEME.md`. It has pointers on how to correctly configure weather, as well as other aspects of the app.

**Comment by owlstack** [comment]
Thank you so much! As for how I came across this repo, I was searching for Magic Mirror and C# (A language I'm familiar with). I think yours was the only result. Thanks!
