### ISSUE TITLE
Could you provide (brief) instructions on the hardware setup you use with this?

### ISSUE THREAD

**Issue by tevert** [IEvangelist/Mirror#3]

**Comment by IEvangelist** [comment]
I plan on doing a step-by-step guide to fully constructing this from the ground up, including but not limited to the hardware, the construction and deployment process... but I was going to do that in a blog series first.

**Comment by tevert** [comment]
Great, you can close this one if you want. Unless you want the reminder to update README.md or something.

**Comment by IEvangelist** [comment]
https://ievangelist.github.io/blog/building-a-magic-mirror/
