### ISSUE TITLE
How  can I add GoogleCalender?

### ISSUE THREAD

**Issue by ghost** [IEvangelist/Mirror#4]
Hey,
How do I add google calendar?
I have a link to the calendar and enter this into the `configuration.resw` in raw form, but this does not work. Then I entered this here:
```
{
   "Url": "Https://calendar.google.com/calendar/ical/blub/bla/basic.ics ",
   "Username": "",
   "Password": "",
   "IsUsingCredentials": false
}
```
But that did not work also.

Sorry, am a noob

**Comment by IEvangelist** [comment]
Hi @gerrus,

I'm not sure, have you tried applying credentials? Here are some things to try:

- Try providing a `Username` and corresponding `Password`, omit the `IsUsingCredentials`
- Open your favorite browser and paste the `Url` in, if it loads there it should also work in the `Mirror` app

Ironically, you're not the only one experiencing this issue. https://github.com/IEvangelist/Mirror/issues/5 was reported a few hours after yours. I'll try setting up a google calendar myself and see what happens. Also, in attempting to put `https://calendar.google.com/calendar/ical/blub/bla/basic.ics` I end up with the following:

![image](https://cloud.githubusercontent.com/assets/7679720/25618307/195d5286-2f0c-11e7-97ba-abb183a24edf.png)

However, I would have expected `JSON` - again, I assume you need to provide credentials. Please report back your findings.

**Comment by ghost** [comment]
Hello IEvangelist,

The problem is not the link to the calendar. The link from above is wrong with intent.
Here is the exception:

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Mirror.Core.CalendarConfig]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
> To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
> Path 'Url', line 2, position 6.

And here is my real JSON string:

```
{
"Url":"https://calendar.google.com/calendar/ical/**my - creds**/basic.ics",
"Username":"",
"Password":"",
}
```

The `JSON` string I have so in the `Configuration.resw` under Calendars purely copied. Is this perhaps wrong?

Thank you!

**Comment by IEvangelist** [comment]
Hi @gerrus,

Ah, yes... it needs to copied over as an array. For example:

```
[{
"Url":"https://calendar.google.com/calendar/ical/**my - creds**/basic.ics",
"Username":"",
"Password":"",
}]
```
The intent was to aggregate calendars into one, and sort by date. Ideally, if you have other calendars you could add multiple configs within the array.

```
[{
"Url":"https://calendar.google.com/calendar/ical/**my - creds**/basic.ics",
"Username":"",
"Password":"",
},
{
 "Url":"https://some other path/basic.ics"
}]
```

**Comment by ghost** [comment]
Thank you so much! Now everything works very good!
Now I will try to make my own mirror. Your project is an example for me
Thanks again!
