### ISSUE TITLE
Calendars

### ISSUE THREAD

**Issue by D4rkF4ce** [IEvangelist/Mirror#5]
Hey!

I have downloaded your project. first of all very good job man!
But i am not able to add my google calendar to the mirror.

Can u help`

Thx BR,
Dark!

**Comment by IEvangelist** [comment]
Thank you for your kind words...I'm going to close this as I'm looking into a seemingly related issue https://github.com/IEvangelist/Mirror/issues/4.

**Comment by D4rkF4ce** [comment]
I get a diffrent error: "The time zone ID 'Europe/Vienna' was not found on the local computer."
after `await loader.LoadAsync();` in MainPage.xaml.cs

**Comment by IEvangelist** [comment]
The exception is being recognized there but the calendar service is throwing that error, when the calendar is being deserialized -- from within the [TimeZoneParser.Parse](https://github.com/IEvangelist/Mirror/blob/master/Mirror/Calendar/TimeZoneParser.cs#L21) method. Try putting a break point there to ensure this assumption.

On your local branch you could do a replacement, if the parser is given the `"Europe/Vienna"` string, you could replace it with one that aligns with [this spec](https://msdn.microsoft.com/en-us/library/gg154758.aspx)? Please report back.

**Comment by D4rkF4ce** [comment]
Yes i have changed the TimeZoneParser Parse Method and it worked :)

```
        public static TimeZoneInfo Parse(Dictionary<string, List<string>> parameters)
        {
            if (parameters == null)
            {
                return null;
            }

            if (parameters.ContainsKey(TimeZoneId) && parameters[TimeZoneId].Count == 1)
            {
                var scrubbedValue = ScrubTimeZone(parameters[TimeZoneId][0]);
                string timezone = scrubbedValue;
                if (scrubbedValue == "Europe/Vienna")
                    timezone = "Central European Standard Time";

                return TimeZoneInfo.FindSystemTimeZoneById(timezone);
            }

            return null;
        }
```

To see all TimeZoneIds on machine:

```
foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
                Debug.WriteLine(z.Id);
```

Maybe it makes sense to put a paramter into the settings file for optional using?!
If I have some time left i will refactor the mehtod.

If somebody have the same issue here is a list of all IDs:

Dateline Standard Time
UTC-11
Aleutian Standard Time
Hawaiian Standard Time
Marquesas Standard Time
Alaskan Standard Time
UTC-09
UTC-08
Pacific Standard Time (Mexico)
Pacific Standard Time
US Mountain Standard Time
Mountain Standard Time (Mexico)
Mountain Standard Time
Central Standard Time
Central Standard Time (Mexico)
Central America Standard Time
Easter Island Standard Time
Canada Central Standard Time
SA Pacific Standard Time
Eastern Standard Time (Mexico)
Eastern Standard Time
Haiti Standard Time
Cuba Standard Time
US Eastern Standard Time
Paraguay Standard Time
Atlantic Standard Time
Venezuela Standard Time
Central Brazilian Standard Time
SA Western Standard Time
Pacific SA Standard Time
Turks And Caicos Standard Time
Newfoundland Standard Time
Tocantins Standard Time
E. South America Standard Time
Argentina Standard Time
SA Eastern Standard Time
Greenland Standard Time
Montevideo Standard Time
Magallanes Standard Time
Bahia Standard Time
Saint Pierre Standard Time
UTC-02
Mid-Atlantic Standard Time
Azores Standard Time
Cape Verde Standard Time
UTC
Morocco Standard Time
GMT Standard Time
Greenwich Standard Time
W. Europe Standard Time
Central Europe Standard Time
Romance Standard Time
Central European Standard Time
W. Central Africa Standard Time
Namibia Standard Time
Jordan Standard Time
GTB Standard Time
Middle East Standard Time
E. Europe Standard Time
Syria Standard Time
West Bank Standard Time
South Africa Standard Time
FLE Standard Time
Israel Standard Time
Egypt Standard Time
Kaliningrad Standard Time
Libya Standard Time
Arabic Standard Time
Turkey Standard Time
Arab Standard Time
Belarus Standard Time
Russian Standard Time
E. Africa Standard Time
Iran Standard Time
Arabian Standard Time
Astrakhan Standard Time
Azerbaijan Standard Time
Caucasus Standard Time
Russia Time Zone 3
Mauritius Standard Time
Saratov Standard Time
Georgian Standard Time
Afghanistan Standard Time
West Asia Standard Time
Pakistan Standard Time
Ekaterinburg Standard Time
India Standard Time
Sri Lanka Standard Time
Nepal Standard Time
Central Asia Standard Time
Bangladesh Standard Time
Omsk Standard Time
Myanmar Standard Time
SE Asia Standard Time
Altai Standard Time
W. Mongolia Standard Time
North Asia Standard Time
N. Central Asia Standard Time
Tomsk Standard Time
North Asia East Standard Time
Singapore Standard Time
China Standard Time
W. Australia Standard Time
Taipei Standard Time
Ulaanbaatar Standard Time
North Korea Standard Time
Aus Central W. Standard Time
Transbaikal Standard Time
Yakutsk Standard Time
Tokyo Standard Time
Korea Standard Time
Cen. Australia Standard Time
AUS Central Standard Time
E. Australia Standard Time
AUS Eastern Standard Time
West Pacific Standard Time
Tasmania Standard Time
Vladivostok Standard Time
Lord Howe Standard Time
Bougainville Standard Time
Magadan Standard Time
Norfolk Standard Time
Sakhalin Standard Time
Central Pacific Standard Time
Russia Time Zone 10
Russia Time Zone 11
New Zealand Standard Time
Fiji Standard Time
UTC+12
Kamchatka Standard Time
Chatham Islands Standard Time
UTC+13
Tonga Standard Time
Samoa Standard Time
Line Islands Standard Time

BR,
Dark!

**Comment by IEvangelist** [comment]
I think that you actually want `"W. Europe Standard Time"` instead. I am considering pulling in [nodatime](https://github.com/jskeet/nodatime), as I believe this might be able to more easily and consistently handle this. Actually, it looks like all we will need is this [TimeZoneConverter](https://github.com/mj1856/TimeZoneConverter). I'll add that as part of my next commit.

**Comment by IEvangelist** [comment]
https://github.com/IEvangelist/Mirror/commit/10d9ecbc77b617cf2ab5f919e068d6294da816db addresses issue for future users...
