### ISSUE TITLE
TryParseExtensions

### ISSUE THREAD

**Issue by D4rkF4ce** [IEvangelist/Mirror#6]
Me again..

I am not able to build the whole solution. 
I get one more error in TryParseExtension:

```
 public static T TryParse<T>(this string value, ParseDelegate<T> parse)
            where T : struct => parse(value as string, out var result) ? result : default(T);
```

i cannot init the "var"-result in the lambda expression.
See screenshot below:

![error](https://cloud.githubusercontent.com/assets/8313770/25656092/c5ce3b7a-2ff7-11e7-87ef-a79c255450a8.PNG)

Can someone pls explain me this error. I dont know how to solve it. As Workaround a have comment out this method and the call from the Emotion Enum. But then i cannot use "How do i look" because the Mirror is using this Method for the response to my question.

I am using VS2015 up-to-date

Thx,BR,
Dark!

**Comment by D4rkF4ce** [comment]
OK i got it 

The current solution is in C# 7.0 (for win iot core) i am working with 6.0 in VS2015

Known issue:
https://stackoverflow.com/questions/31724163/tryparse-with-out-var-param
_"Declaration expressions was cut from C# 6.0 and wasn't shipped in the final release."_


i have changed it to:

```
        public static T TryParse<T>(this string value, ParseDelegate<T> parse)
            where T : struct
        {
            T result;
            return parse(value as string, out result) ? result : default(T);
        }
```

BR,
Dark!

**Comment by IEvangelist** [comment]
Ah, yes... truthfully - I didn't consider this to be an issue. I upgraded to using __Visual Studio 2017__, and with that we can leverage __C# 7__ ([I blogged about __C# 7__ here](http://davidpine.net/blog/exploring-csharp-seven/)). You should download and install __Visual Studio 2017__ community edition, it is free.
