### ISSUE TITLE
The speech privacy policy was not accepted

### ISSUE THREAD

**Issue by D4rkF4ce** [IEvangelist/Mirror#7]
Hey IEvangelist sorry for my question again but i can't find anything on google..

I am so fascinated by your project that I decided to build my own SmartMirror with voice recognition.

Components:
microsoft hd-lifecam 3000
Raspberry Pi3
22" HDMI monitor

I have connected all togther set the microphone & webcam capabilities but after deployment to raspberry pi i get this error:

"System.Runtime.InteropServices.COMException" in HiGHTECHNiX.SmartMirror.UI.exe
WinRT-Informationen: The speech privacy policy was not accepted prior to attempting a speech recognition.

on my dev machine everything worked fine.
Can u pls help me?

BR,
Dark!

**Comment by IEvangelist** [comment]
Hi @D4rkF4ce,

No worries, that's what "Issues" are for. I'm trying to remember exactly what I did to solve this. I know that one thing is for sure, I had to do something as well - and there was no "programmatic approach" available. Things I would suggest that you attempt in order of probability:

- Use the ["Device Portal"](https://developer.microsoft.com/en-us/windows/iot/docs/deviceportal) (or [this](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal) to remote into the Raspberry Pi's Windows 10 IoT Core, and attempt configuring it from there... not sure it's a setting?
- Ensure that you're in ["Developer Mode"](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)
- Connect USB mouse and keyboard to Raspberry Pi 3
  - Start your device, and wait for the "Windows 10 IoT Core - Default App" to launch
  - Explore the various settings looking for anything related to this.

**Comment by D4rkF4ce** [comment]
Ok so after some try around and information how to work with the speech recognition. I think i could solve the problem.

I have changed the app default language to "de-DE" in my appmanifest
(For getting date and time in the correct format.)

But this triggered a "System.Runtime.InteropServices.COMException" exception because the speech recognition tries to access the German language pack. Which is not installed at the Pi.

Here you have to proceed as follows to "install" other languages ​​on Pi:
[http://stackoverflow.com/questions/41109796/add-language-pack-to-windows-iot-core](http://stackoverflow.com/questions/41109796/add-language-pack-to-windows-iot-core)

Now I could inizialisieren the speech recognition but still not execute ...

Then I have measured how long the speech recognition needed to compile the necessary gramars & constraints .. TATAAA it takes a while so I have adjusted my logic again and now it runs as desired.

1. Init Voice recognition
2. Compile necessary Contraints & Grammars
3. Start continuous speech recognition
4. On ResultGenerated i handle the command and recompile the Grammars for the next tasks

Thx for the hint in the right direction
Dark!

**Comment by IEvangelist** [comment]
Happy to help!
