### ISSUE TITLE
Do.WithRetry doesn't actually retry

### ISSUE THREAD

**Issue by HappyNomad** [IEvangelist/Mirror#9]
https://github.com/IEvangelist/Mirror/blob/01f536073be65624c56a857ace363586a5416f66/Mirror.Core/Do.cs#L20

Hi, I came across this code via [a StackOverflow question](https://stackoverflow.com/questions/38309165).  It seems to me that the code doesn't actually retry anything.  It performs the action just once.

**Comment by IEvangelist** [comment]
Hmmm, it actually does retry though. Let's talk it through quick... so here is the code: 

```csharp
public static async Task<T> WithRetry<T>(Func<Task<T>> action, int retryCount = 3)
{
    int retries = 0;
    while (true)
    {
        try
        {
            return await action().ConfigureAwait(false);                    
        }
        catch when (++ retries <= retryCount)
        {
            // Ease up a bit...
            await Delay(500).ConfigureAwait(false);
            return await TaskCache<T>.Default;
        }
    }
}
```

Scenario 1, if the given `action` is successful the first invocation to it... we're done, no reason to retry and we exit the `while (true)` loop.

Scenario 2, if the given `action` throws (imagine a transient error) on the first invocation, we're in a `while` loop... the `catchwhen` will enter as retries is only incremented to `1` and still less than the default `retryCount` of `3`. We then await 500 milliseconds, oh! I see 👀 ... the `return await TaskCache<T>.Default` is actually wrong. That should be removed, that is a bug... nice catch.
